/*
 * 'Shell commands' plugin for Obsidian.
 * Copyright (C) 2021 - 2024 Jarkko Linnanvirta
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.0 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * Contact the author (Jarkko Linnanvirta): https://github.com/Taitava/
 */

import {
    getIconIds,
    setIcon,
} from "obsidian";

/**
 * A wrapper for Obsidian's setIcon(), but with the difference that this one does not need a container as a parameter.
 */
export function getIconHTML(icon_id: string) {
    if (!icon_id) {
        return "";
    }
    const icon_container = document.body.createEl("div"); // A temporary element, will be deleted soon. Not nice to create a temporary element in the body, but I don't know any better way.
    setIcon(icon_container, icon_id);
    const icon_html = icon_container.innerHTML;
    icon_container.remove();
    return icon_html;
}

export type SC_Icon = {
    iconId: string,
    displayName: string
};

const unsortedIconList = getIconIds().map((iconId: string): SC_Icon => {
    const icon = {
        iconId: iconId,
        displayName: iconId,
    };
    if (iconId.match(/^lucide-/)) {
        // Remove the `lucide-` prefix from `displayValue`.
        icon.displayName = iconId.replace(/^lucide-/, '');
    }
    return icon;
});

export const SORTED_ICON_LIST: SC_Icon[] = unsortedIconList.sort((iconA: SC_Icon, iconB: SC_Icon) => {
    if (iconA.displayName === iconB.displayName) {
        return 0;
    } else if (iconA.displayName > iconB.displayName) {
        return 1;
    } else {
        return -1;
    }
});

/**
 * The SC plugin up to version 0.22.0 used old style icon names. Those are still usable in Obsidian, but from SC 0.23.0 onwards the plugin migrates the icon names so that they can be found from the list returned by Obsidian's `getIconIds()`.
 *
 * Some icon names have only changed so that their name is prefixed with `lucide-`, but there are a few whose names have changed completely, e.g. `any-key` --> `lucide-plus-circle`.
 *
 * The following script was used to compile the migration list. You'll have to dig `AUGMENTED_ICON_LIST` from the history of this Git repository, as it was removed by the same commit that created this migration.
 * ```TypeScript
 *         const iconComparison: string[] = [];
 *         for (const oldIcon of AUGMENTED_ICON_LIST) {
 *             if (getIconIds().contains(oldIcon)) {
 *                 iconComparison.push(oldIcon + " = OK");
 *             }
 *             else {
 *                 const oldIconHTML = getIconHTML(oldIcon);
 *                 let foundWithAnotherName = false;
 *                 for (const newIcon of getIconIds()) {
 *                     const newIconHTML = getIconHTML(newIcon);
 *                     if (newIconHTML === oldIconHTML) {
 *                         iconComparison.push(oldIcon + " = Found as " + newIcon);
 *                         foundWithAnotherName = true;
 *                         break;
 *                     }
 *                 }
 *                 if (!foundWithAnotherName) {
 *                     iconComparison.push(oldIcon + " = NOT FOUND!");
 *                 }
 *             }
 *         }
 * ```
 */
export const ICON_MIGRATIONS: {[key: string]: string|null} = {
    /* These icons do not need to be renamed, as they exist in the list returned by `getIconIds()`:
    bracket-glyph, broken-link, check-small, dice, heading-glyph, help, left-arrow, link, link-glyph, lucide-clock, lucide-cloud,
    lucide-cross, lucide-folder, lucide-info, lucide-languages, lucide-link, lucide-pencil, lucide-pin, lucide-search, lucide-star,
    lucide-trash, open-vault, paused, right-arrow, right-triangle, sheets-in-box, star-list, stretch-horizontal, stretch-vertical,
    sync-small, uppercase-lowercase-a, vault
    */
    
    // Icon names that were contained in SC 0.22.0 icon list, but that never worked. Disable any occurrences of these.
    'file-x-2': null,
    'link-2-off': null,
    'logo-crystal': null,
    'sortAsc': null,
    'sortDesc': null,
    
    // Icons that are present in the `getIconIds()` list with another name:
    'activity': 'lucide-activity',
    'airplay': 'lucide-airplay',
    'alarm-check': 'lucide-alarm-check',
    'alarm-clock': 'lucide-alarm-clock',
    'alarm-clock-off': 'lucide-alarm-clock-off',
    'alarm-minus': 'lucide-alarm-minus',
    'alarm-plus': 'lucide-alarm-plus',
    'album': 'lucide-album',
    'alert-circle': 'lucide-alert-circle',
    'alert-octagon': 'lucide-alert-octagon',
    'alert-triangle': 'lucide-alert-triangle',
    'align-center': 'lucide-align-center',
    'align-center-horizontal': 'lucide-align-center-horizontal',
    'align-center-vertical': 'lucide-align-center-vertical',
    'align-end-horizontal': 'lucide-align-end-horizontal',
    'align-end-vertical': 'lucide-align-end-vertical',
    'align-horizontal-distribute-center': 'lucide-align-horizontal-distribute-center',
    'align-horizontal-distribute-end': 'lucide-align-horizontal-distribute-end',
    'align-horizontal-distribute-start': 'lucide-align-horizontal-distribute-start',
    'align-horizontal-justify-center': 'lucide-align-horizontal-justify-center',
    'align-horizontal-justify-end': 'lucide-align-horizontal-justify-end',
    'align-horizontal-justify-start': 'lucide-align-horizontal-justify-start',
    'align-horizontal-space-around': 'lucide-align-horizontal-space-around',
    'align-horizontal-space-between': 'lucide-align-horizontal-space-between',
    'align-justify': 'lucide-align-justify',
    'align-left': 'lucide-align-left',
    'align-right': 'lucide-align-right',
    'align-start-horizontal': 'lucide-align-start-horizontal',
    'align-start-vertical': 'lucide-align-start-vertical',
    'align-vertical-distribute-center': 'lucide-align-vertical-distribute-center',
    'align-vertical-distribute-end': 'lucide-align-vertical-distribute-end',
    'align-vertical-distribute-start': 'lucide-align-vertical-distribute-start',
    'align-vertical-justify-center': 'lucide-align-vertical-justify-center',
    'align-vertical-justify-end': 'lucide-align-vertical-justify-end',
    'align-vertical-justify-start': 'lucide-align-vertical-justify-start',
    'align-vertical-space-around': 'lucide-align-vertical-space-around',
    'align-vertical-space-between': 'lucide-align-vertical-space-between',
    'anchor': 'lucide-anchor',
    'any-key': 'lucide-plus-circle',
    'aperture': 'lucide-aperture',
    'archive': 'lucide-archive',
    'arrow-big-down': 'lucide-arrow-big-down',
    'arrow-big-left': 'lucide-arrow-big-left',
    'arrow-big-right': 'lucide-arrow-big-right',
    'arrow-big-up': 'lucide-arrow-big-up',
    'arrow-down': 'lucide-arrow-down',
    'arrow-down-circle': 'lucide-arrow-down-circle',
    'arrow-down-left': 'lucide-arrow-down-left',
    'arrow-down-right': 'lucide-arrow-down-right',
    'arrow-left': 'lucide-arrow-left',
    'arrow-left-circle': 'lucide-arrow-left-circle',
    'arrow-left-right': 'lucide-arrow-left-right',
    'arrow-right': 'lucide-arrow-right',
    'arrow-right-circle': 'lucide-arrow-right-circle',
    'arrow-up': 'lucide-arrow-up',
    'arrow-up-circle': 'lucide-arrow-up-circle',
    'arrow-up-left': 'lucide-arrow-up-left',
    'arrow-up-right': 'lucide-arrow-up-right',
    'asterisk': 'lucide-asterisk',
    'at-sign': 'lucide-at-sign',
    'audio-file': 'lucide-file-audio',
    'award': 'lucide-award',
    'axe': 'lucide-axe',
    'banknote': 'lucide-banknote',
    'bar-chart': 'lucide-bar-chart',
    'bar-chart-2': 'lucide-bar-chart-2',
    'baseline': 'lucide-baseline',
    'battery': 'lucide-battery',
    'battery-charging': 'lucide-battery-charging',
    'battery-full': 'lucide-battery-full',
    'battery-low': 'lucide-battery-low',
    'battery-medium': 'lucide-battery-medium',
    'beaker': 'lucide-beaker',
    'bell': 'lucide-bell',
    'bell-minus': 'lucide-bell-minus',
    'bell-off': 'lucide-bell-off',
    'bell-plus': 'lucide-bell-plus',
    'bell-ring': 'lucide-bell-ring',
    'bike': 'lucide-bike',
    'binary': 'lucide-binary',
    'bitcoin': 'lucide-bitcoin',
    'blocks': 'lucide-layout-list',
    'bluetooth': 'lucide-bluetooth',
    'bluetooth-connected': 'lucide-bluetooth-connected',
    'bluetooth-off': 'lucide-bluetooth-off',
    'bluetooth-searching': 'lucide-bluetooth-searching',
    'bold': 'lucide-bold',
    'bold-glyph': 'lucide-bold',
    'book': 'lucide-book',
    'book-open': 'lucide-book-open',
    'bookmark': 'lucide-bookmark',
    'bookmark-minus': 'lucide-bookmark-minus',
    'bookmark-plus': 'lucide-bookmark-plus',
    'bot': 'lucide-bot',
    'box': 'lucide-box',
    'box-select': 'lucide-box-select',
    'briefcase': 'lucide-briefcase',
    'brush': 'lucide-brush',
    'bug': 'lucide-bug',
    'building': 'lucide-building',
    'building-2': 'lucide-building-2',
    'bullet-list': 'lucide-list',
    'bullet-list-glyph': 'lucide-list',
    'bus': 'lucide-bus',
    'calculator': 'lucide-calculator',
    'calendar': 'lucide-calendar',
    'calendar-with-checkmark': 'lucide-calendar-check',
    'camera': 'lucide-camera',
    'camera-off': 'lucide-camera-off',
    'car': 'lucide-car',
    'carrot': 'lucide-carrot',
    'cast': 'lucide-cast',
    'check': 'lucide-check',
    'check-circle': 'lucide-check-circle',
    'check-circle-2': 'lucide-check-circle-2',
    'check-in-circle': 'lucide-check-circle-2',
    'check-square': 'lucide-check-square',
    'checkbox-glyph': 'lucide-check-square',
    'checkmark': 'lucide-check',
    'chevron-down': 'lucide-chevron-down',
    'chevron-first': 'lucide-chevron-first',
    'chevron-last': 'lucide-chevron-last',
    'chevron-left': 'lucide-chevron-left',
    'chevron-right': 'lucide-chevron-right',
    'chevron-up': 'lucide-chevron-up',
    'chevrons-down': 'lucide-chevrons-down',
    'chevrons-down-up': 'lucide-chevrons-down-up',
    'chevrons-left': 'lucide-chevrons-left',
    'chevrons-right': 'lucide-chevrons-right',
    'chevrons-up': 'lucide-chevrons-up',
    'chevrons-up-down': 'lucide-chevrons-up-down',
    'chrome': 'lucide-chrome',
    'circle': 'lucide-circle',
    'circle-slashed': 'lucide-circle-slashed',
    'clipboard': 'lucide-clipboard',
    'clipboard-check': 'lucide-clipboard-check',
    'clipboard-copy': 'lucide-clipboard-copy',
    'clipboard-list': 'lucide-clipboard-list',
    'clipboard-x': 'lucide-clipboard-x',
    'clock': 'lucide-clock',
    'clock-1': 'lucide-clock-1',
    'clock-10': 'lucide-clock-10',
    'clock-11': 'lucide-clock-11',
    'clock-12': 'lucide-clock-12',
    'clock-2': 'lucide-clock-2',
    'clock-3': 'lucide-clock-3',
    'clock-4': 'lucide-clock-4',
    'clock-5': 'lucide-clock-5',
    'clock-6': 'lucide-clock-6',
    'clock-7': 'lucide-clock-7',
    'clock-8': 'lucide-clock-8',
    'clock-9': 'lucide-clock-9',
    'cloud': 'lucide-cloud',
    'cloud-drizzle': 'lucide-cloud-drizzle',
    'cloud-fog': 'lucide-cloud-fog',
    'cloud-hail': 'lucide-cloud-hail',
    'cloud-lightning': 'lucide-cloud-lightning',
    'cloud-moon': 'lucide-cloud-moon',
    'cloud-off': 'lucide-cloud-off',
    'cloud-rain': 'lucide-cloud-rain',
    'cloud-rain-wind': 'lucide-cloud-rain-wind',
    'cloud-snow': 'lucide-cloud-snow',
    'cloud-sun': 'lucide-cloud-sun',
    'cloudy': 'lucide-cloudy',
    'clover': 'lucide-clover',
    'code': 'lucide-code',
    'code-2': 'lucide-code-2',
    'code-glyph': 'lucide-code-2',
    'codepen': 'lucide-codepen',
    'codesandbox': 'lucide-codesandbox',
    'coffee': 'lucide-coffee',
    'coins': 'lucide-coins',
    'columns': 'lucide-columns',
    'command': 'lucide-command',
    'compass': 'lucide-compass',
    'contact': 'lucide-contact',
    'contrast': 'lucide-contrast',
    'cookie': 'lucide-cookie',
    'copy': 'lucide-copy',
    'copyleft': 'lucide-copyleft',
    'copyright': 'lucide-copyright',
    'corner-down-left': 'lucide-corner-down-left',
    'corner-down-right': 'lucide-corner-down-right',
    'corner-left-down': 'lucide-corner-left-down',
    'corner-left-up': 'lucide-corner-left-up',
    'corner-right-down': 'lucide-corner-right-down',
    'corner-right-up': 'lucide-corner-right-up',
    'corner-up-left': 'lucide-corner-up-left',
    'corner-up-right': 'lucide-corner-up-right',
    'cpu': 'lucide-cpu',
    'create-new': 'lucide-edit',
    'credit-card': 'lucide-credit-card',
    'crop': 'lucide-crop',
    'cross': 'lucide-x',
    'cross-in-box': 'lucide-x-square',
    'crossed-star': 'lucide-star-off',
    'crosshair': 'lucide-crosshair',
    'crown': 'lucide-crown',
    'currency': 'lucide-currency',
    'database': 'lucide-database',
    'delete': 'lucide-delete',
    'dice-1': 'lucide-dice-1',
    'dice-2': 'lucide-dice-2',
    'dice-3': 'lucide-dice-3',
    'dice-4': 'lucide-dice-4',
    'dice-5': 'lucide-dice-5',
    'dice-6': 'lucide-dice-6',
    'disc': 'lucide-disc',
    'divide': 'lucide-divide',
    'divide-circle': 'lucide-divide-circle',
    'divide-square': 'lucide-divide-square',
    'document': 'lucide-file',
    'documents': 'lucide-files',
    'dollar-sign': 'lucide-dollar-sign',
    'dot-network': 'lucide-git-fork',
    'double-down-arrow-glyph': 'lucide-chevrons-down',
    'double-up-arrow-glyph': 'lucide-chevrons-up',
    'down-arrow-with-tail': 'lucide-arrow-down',
    'down-chevron-glyph': 'lucide-chevron-down',
    'download': 'lucide-download',
    'download-cloud': 'lucide-download-cloud',
    'dribbble': 'lucide-dribbble',
    'droplet': 'lucide-droplet',
    'droplets': 'lucide-droplets',
    'drumstick': 'lucide-drumstick',
    'edit': 'lucide-edit',
    'edit-2': 'lucide-edit-2',
    'edit-3': 'lucide-edit-3',
    'egg': 'lucide-egg',
    'enter': 'lucide-log-in',
    'equal': 'lucide-equal',
    'equal-not': 'lucide-equal-not',
    'eraser': 'lucide-eraser',
    'euro': 'lucide-euro',
    'exit-fullscreen': 'lucide-minimize',
    'expand': 'lucide-expand',
    'expand-vertically': 'lucide-move-vertical',
    'external-link': 'lucide-external-link',
    'eye': 'lucide-eye',
    'eye-off': 'lucide-eye-off',
    'facebook': 'lucide-facebook',
    'fast-forward': 'lucide-fast-forward',
    'feather': 'lucide-feather',
    'figma': 'lucide-figma',
    'file': 'lucide-file',
    'file-check': 'lucide-file-check',
    'file-check-2': 'lucide-file-check-2',
    'file-code': 'lucide-file-code',
    'file-digit': 'lucide-file-digit',
    'file-input': 'lucide-file-input',
    'file-minus': 'lucide-file-minus',
    'file-minus-2': 'lucide-file-minus-2',
    'file-output': 'lucide-file-output',
    'file-plus': 'lucide-file-plus',
    'file-plus-2': 'lucide-file-plus-2',
    'file-search': 'lucide-file-search',
    'file-text': 'lucide-file-text',
    'file-x': 'lucide-file-x',
    'files': 'lucide-files',
    'filled-pin': 'lucide-pin',
    'film': 'lucide-film',
    'filter': 'lucide-filter',
    'flag': 'lucide-flag',
    'flag-off': 'lucide-flag-off',
    'flag-triangle-left': 'lucide-flag-triangle-left',
    'flag-triangle-right': 'lucide-flag-triangle-right',
    'flame': 'lucide-flame',
    'flashlight': 'lucide-flashlight',
    'flashlight-off': 'lucide-flashlight-off',
    'flask-conical': 'lucide-flask-conical',
    'flask-round': 'lucide-flask-round',
    'folder': 'lucide-folder-open',
    'folder-minus': 'lucide-folder-minus',
    'folder-open': 'lucide-folder-open',
    'folder-plus': 'lucide-folder-plus',
    'form-input': 'lucide-form-input',
    'forward': 'lucide-forward',
    'forward-arrow': 'lucide-forward',
    'frame': 'lucide-frame',
    'framer': 'lucide-framer',
    'frown': 'lucide-frown',
    'fullscreen': 'lucide-maximize',
    'function-square': 'lucide-function-square',
    'gamepad': 'lucide-gamepad',
    'gamepad-2': 'lucide-gamepad-2',
    'gauge': 'lucide-gauge',
    'gavel': 'lucide-gavel',
    'gear': 'lucide-settings',
    'gem': 'lucide-gem',
    'ghost': 'lucide-ghost',
    'gift': 'lucide-gift',
    'git-branch': 'lucide-git-branch',
    'git-branch-plus': 'lucide-git-branch-plus',
    'git-commit': 'lucide-git-commit',
    'git-fork': 'lucide-git-fork',
    'git-merge': 'lucide-git-merge',
    'git-pull-request': 'lucide-git-pull-request',
    'github': 'lucide-github',
    'gitlab': 'lucide-gitlab',
    'glasses': 'lucide-glasses',
    'globe': 'lucide-globe',
    'globe-2': 'lucide-globe-2',
    'go-to-file': 'lucide-file-input',
    'grab': 'lucide-grab',
    'graduation-cap': 'lucide-graduation-cap',
    'grid': 'lucide-grid',
    'grip-horizontal': 'lucide-grip-horizontal',
    'grip-vertical': 'lucide-grip-vertical',
    'hammer': 'lucide-hammer',
    'hand': 'lucide-hand',
    'hand-metal': 'lucide-hand-metal',
    'hard-drive': 'lucide-hard-drive',
    'hard-hat': 'lucide-hard-hat',
    'hash': 'lucide-hash',
    'hashtag': 'lucide-hash',
    'haze': 'lucide-haze',
    'headphones': 'lucide-headphones',
    'heart': 'lucide-heart',
    'help-circle': 'lucide-help-circle',
    'hexagon': 'lucide-hexagon',
    'highlight-glyph': 'lucide-highlighter',
    'highlighter': 'lucide-highlighter',
    'history': 'lucide-history',
    'home': 'lucide-home',
    'horizontal-split': 'lucide-separator-horizontal',
    'image': 'lucide-image',
    'image-file': 'lucide-image',
    'image-glyph': 'lucide-paperclip',
    'image-minus': 'lucide-image-minus',
    'image-off': 'lucide-image-off',
    'image-plus': 'lucide-image-plus',
    'import': 'lucide-import',
    'inbox': 'lucide-inbox',
    'indent': 'lucide-indent',
    'indent-glyph': 'lucide-indent',
    'indian-rupee': 'lucide-indian-rupee',
    'infinity': 'lucide-infinity',
    'info': 'lucide-info',
    'inspect': 'lucide-inspect',
    'instagram': 'lucide-instagram',
    'install': 'lucide-download-cloud',
    'italic': 'lucide-italic',
    'italic-glyph': 'lucide-italic',
    'japanese-yen': 'lucide-japanese-yen',
    'key': 'lucide-key',
    'keyboard': 'lucide-keyboard',
    'keyboard-glyph': 'lucide-keyboard',
    'landmark': 'lucide-landmark',
    'languages': 'lucide-languages',
    'laptop': 'lucide-laptop',
    'laptop-2': 'lucide-laptop-2',
    'lasso': 'lucide-lasso',
    'lasso-select': 'lucide-lasso-select',
    'layers': 'lucide-layers',
    'layout': 'lucide-layout',
    'layout-dashboard': 'lucide-layout-dashboard',
    'layout-grid': 'lucide-layout-grid',
    'layout-list': 'lucide-layout-list',
    'layout-template': 'lucide-layout-template',
    'left-arrow-with-tail': 'lucide-arrow-left',
    'left-chevron-glyph': 'lucide-chevron-left',
    'library': 'lucide-library',
    'life-buoy': 'lucide-life-buoy',
    'lightbulb': 'lucide-lightbulb',
    'lightbulb-off': 'lucide-lightbulb-off',
    'lines-of-text': 'lucide-align-left',
    'link-2': 'lucide-link-2',
    'linkedin': 'lucide-linkedin',
    'list': 'lucide-list',
    'list-checks': 'lucide-list-checks',
    'list-minus': 'lucide-list-minus',
    'list-ordered': 'lucide-list-ordered',
    'list-plus': 'lucide-list-plus',
    'list-x': 'lucide-list-x',
    'loader': 'lucide-loader',
    'loader-2': 'lucide-loader-2',
    'locate': 'lucide-locate',
    'locate-fixed': 'lucide-locate-fixed',
    'locate-off': 'lucide-locate-off',
    'lock': 'lucide-lock',
    'log-in': 'lucide-log-in',
    'log-out': 'lucide-log-out',
    'magnifying-glass': 'lucide-search',
    'mail': 'lucide-mail',
    'map': 'lucide-map',
    'map-pin': 'lucide-map-pin',
    'maximize': 'lucide-maximize',
    'maximize-2': 'lucide-maximize-2',
    'megaphone': 'lucide-megaphone',
    'meh': 'lucide-meh',
    'menu': 'lucide-menu',
    'message-circle': 'lucide-message-circle',
    'message-square': 'lucide-message-square',
    'mic': 'lucide-mic',
    'mic-off': 'lucide-mic-off',
    'microphone': 'lucide-mic',
    'microphone-filled': 'lucide-mic',
    'minimize': 'lucide-minimize',
    'minimize-2': 'lucide-minimize-2',
    'minus': 'lucide-minus',
    'minus-circle': 'lucide-minus-circle',
    'minus-square': 'lucide-minus-square',
    'minus-with-circle': 'lucide-minus-circle',
    'monitor': 'lucide-monitor',
    'monitor-off': 'lucide-monitor-off',
    'monitor-speaker': 'lucide-monitor-speaker',
    'moon': 'lucide-moon',
    'more-horizontal': 'lucide-more-horizontal',
    'more-vertical': 'lucide-more-vertical',
    'mountain': 'lucide-mountain',
    'mountain-snow': 'lucide-mountain-snow',
    'mouse': 'lucide-mouse',
    'mouse-pointer': 'lucide-mouse-pointer',
    'mouse-pointer-2': 'lucide-mouse-pointer-2',
    'mouse-pointer-click': 'lucide-mouse-pointer-click',
    'move': 'lucide-move',
    'move-diagonal': 'lucide-move-diagonal',
    'move-diagonal-2': 'lucide-move-diagonal-2',
    'move-horizontal': 'lucide-move-horizontal',
    'move-vertical': 'lucide-move-vertical',
    'music': 'lucide-music',
    'navigation': 'lucide-navigation',
    'navigation-2': 'lucide-navigation-2',
    'network': 'lucide-network',
    'note-glyph': 'lucide-sticky-note',
    'number-list-glyph': 'lucide-list-ordered',
    'octagon': 'lucide-octagon',
    'option': 'lucide-option',
    'outdent': 'lucide-outdent',
    'package': 'lucide-package',
    'package-check': 'lucide-package-check',
    'package-minus': 'lucide-package-minus',
    'package-plus': 'lucide-package-plus',
    'package-search': 'lucide-package-search',
    'package-x': 'lucide-package-x',
    'palette': 'lucide-palette',
    'palmtree': 'lucide-palmtree',
    'pane-layout': 'lucide-layout',
    'paper-plane': 'lucide-send',
    'paperclip': 'lucide-paperclip',
    'pause': 'lucide-pause',
    'pause-circle': 'lucide-pause-circle',
    'pause-octagon': 'lucide-pause-octagon',
    'pdf-file': 'lucide-file-text',
    'pen-tool': 'lucide-pen-tool',
    'pencil': 'lucide-edit-3',
    'percent': 'lucide-percent',
    'percent-sign-glyph': 'lucide-percent',
    'person-standing': 'lucide-person-standing',
    'phone': 'lucide-phone',
    'phone-call': 'lucide-phone-call',
    'phone-forwarded': 'lucide-phone-forwarded',
    'phone-incoming': 'lucide-phone-incoming',
    'phone-missed': 'lucide-phone-missed',
    'phone-off': 'lucide-phone-off',
    'phone-outgoing': 'lucide-phone-outgoing',
    'pie-chart': 'lucide-pie-chart',
    'piggy-bank': 'lucide-piggy-bank',
    'pin': 'lucide-pin',
    'pipette': 'lucide-pipette',
    'plane': 'lucide-plane',
    'play': 'lucide-play',
    'play-circle': 'lucide-play-circle',
    'plug-zap': 'lucide-plug-zap',
    'plus': 'lucide-plus',
    'plus-circle': 'lucide-plus-circle',
    'plus-square': 'lucide-plus-square',
    'plus-with-circle': 'lucide-plus-circle',
    'pocket': 'lucide-pocket',
    'podcast': 'lucide-podcast',
    'pointer': 'lucide-pointer',
    'popup-open': 'lucide-arrow-up-right',
    'pound-sterling': 'lucide-pound-sterling',
    'power': 'lucide-power',
    'power-off': 'lucide-power-off',
    'presentation': 'lucide-monitor',
    'price-tag-glyph': 'lucide-tag',
    'printer': 'lucide-printer',
    'qr-code': 'lucide-qr-code',
    'quote': 'lucide-quote',
    'quote-glyph': 'lucide-quote',
    'radio': 'lucide-radio',
    'radio-receiver': 'lucide-radio-receiver',
    'redo': 'lucide-redo',
    'redo-glyph': 'lucide-redo-2',
    'refresh-ccw': 'lucide-refresh-ccw',
    'refresh-cw': 'lucide-refresh-cw',
    'regex': 'lucide-regex',
    'repeat': 'lucide-repeat',
    'repeat-1': 'lucide-repeat-1',
    'reply': 'lucide-reply',
    'reply-all': 'lucide-reply-all',
    'reset': 'lucide-rotate-ccw',
    'rewind': 'lucide-rewind',
    'right-arrow-with-tail': 'lucide-arrow-right',
    'right-chevron-glyph': 'lucide-chevron-right',
    'rocket': 'lucide-rocket',
    'rocking-chair': 'lucide-rocking-chair',
    'rotate-ccw': 'lucide-rotate-ccw',
    'rotate-cw': 'lucide-rotate-cw',
    'rss': 'lucide-rss',
    'ruler': 'lucide-ruler',
    'run-command': 'lucide-terminal',
    'russian-ruble': 'lucide-russian-ruble',
    'save': 'lucide-save',
    'scale': 'lucide-scale',
    'scan': 'lucide-scan',
    'scan-line': 'lucide-scan-line',
    'scissors': 'lucide-scissors',
    'screen-share': 'lucide-screen-share',
    'screen-share-off': 'lucide-screen-share-off',
    'search': 'lucide-search',
    'send': 'lucide-send',
    'separator-horizontal': 'lucide-separator-horizontal',
    'separator-vertical': 'lucide-separator-vertical',
    'server': 'lucide-server',
    'server-crash': 'lucide-server-crash',
    'server-off': 'lucide-server-off',
    'settings': 'lucide-settings',
    'settings-2': 'lucide-settings-2',
    'share': 'lucide-share',
    'share-2': 'lucide-share-2',
    'sheet': 'lucide-sheet',
    'shield': 'lucide-shield',
    'shield-alert': 'lucide-shield-alert',
    'shield-check': 'lucide-shield-check',
    'shield-close': 'lucide-shield-close',
    'shield-off': 'lucide-shield-off',
    'shirt': 'lucide-shirt',
    'shopping-bag': 'lucide-shopping-bag',
    'shopping-cart': 'lucide-shopping-cart',
    'shovel': 'lucide-shovel',
    'shrink': 'lucide-shrink',
    'shuffle': 'lucide-shuffle',
    'sidebar': 'lucide-sidebar',
    'sidebar-close': 'lucide-sidebar-close',
    'sidebar-open': 'lucide-sidebar-open',
    'sigma': 'lucide-sigma',
    'signal': 'lucide-signal',
    'signal-high': 'lucide-signal-high',
    'signal-low': 'lucide-signal-low',
    'signal-medium': 'lucide-signal-medium',
    'signal-zero': 'lucide-signal-zero',
    'skip-back': 'lucide-skip-back',
    'skip-forward': 'lucide-skip-forward',
    'skull': 'lucide-skull',
    'slack': 'lucide-slack',
    'slash': 'lucide-slash',
    'sliders': 'lucide-sliders',
    'smartphone': 'lucide-smartphone',
    'smartphone-charging': 'lucide-smartphone-charging',
    'smile': 'lucide-smile',
    'snowflake': 'lucide-snowflake',
    'sort-asc': 'lucide-sort-asc',
    'sort-desc': 'lucide-sort-desc',
    'speaker': 'lucide-speaker',
    'sprout': 'lucide-sprout',
    'square': 'lucide-square',
    'stacked-levels': 'lucide-folder-tree',
    'star': 'lucide-star',
    'star-half': 'lucide-star-half',
    'stop-circle': 'lucide-stop-circle',
    'strikethrough': 'lucide-strikethrough',
    'strikethrough-glyph': 'lucide-strikethrough',
    'subscript': 'lucide-subscript',
    'sun': 'lucide-sun',
    'sunrise': 'lucide-sunrise',
    'sunset': 'lucide-sunset',
    'superscript': 'lucide-superscript',
    'swiss-franc': 'lucide-swiss-franc',
    'switch': 'lucide-repeat',
    'switch-camera': 'lucide-switch-camera',
    'sync': 'lucide-refresh-cw',
    'table': 'lucide-table',
    'tablet': 'lucide-tablet',
    'tag': 'lucide-tag',
    'tag-glyph': 'lucide-tag',
    'target': 'lucide-target',
    'tent': 'lucide-tent',
    'terminal': 'lucide-terminal',
    'terminal-square': 'lucide-terminal-square',
    'text-cursor': 'lucide-text-cursor',
    'text-cursor-input': 'lucide-text-cursor-input',
    'thermometer': 'lucide-thermometer',
    'thermometer-snowflake': 'lucide-thermometer-snowflake',
    'thermometer-sun': 'lucide-thermometer-sun',
    'three-horizontal-bars': 'lucide-menu',
    'thumbs-down': 'lucide-thumbs-down',
    'thumbs-up': 'lucide-thumbs-up',
    'ticket': 'lucide-ticket',
    'timer': 'lucide-timer',
    'timer-off': 'lucide-timer-off',
    'timer-reset': 'lucide-timer-reset',
    'toggle-left': 'lucide-toggle-left',
    'toggle-right': 'lucide-toggle-right',
    'tornado': 'lucide-tornado',
    'trash': 'lucide-trash-2',
    'trash-2': 'lucide-trash-2',
    'trello': 'lucide-trello',
    'trending-down': 'lucide-trending-down',
    'trending-up': 'lucide-trending-up',
    'triangle': 'lucide-triangle',
    'truck': 'lucide-truck',
    'tv': 'lucide-tv',
    'tv-2': 'lucide-tv-2',
    'twitch': 'lucide-twitch',
    'twitter': 'lucide-twitter',
    'type': 'lucide-type',
    'umbrella': 'lucide-umbrella',
    'underline': 'lucide-underline',
    'undo': 'lucide-undo',
    'undo-glyph': 'lucide-undo-2',
    'unindent-glyph': 'lucide-outdent',
    'unlink': 'lucide-unlink',
    'unlink-2': 'lucide-unlink-2',
    'unlock': 'lucide-unlock',
    'up-and-down-arrows': 'lucide-move-vertical',
    'up-arrow-with-tail': 'lucide-arrow-up',
    'up-chevron-glyph': 'lucide-chevron-up',
    'upload': 'lucide-upload',
    'upload-cloud': 'lucide-upload-cloud',
    'user': 'lucide-user',
    'user-check': 'lucide-user-check',
    'user-minus': 'lucide-user-minus',
    'user-plus': 'lucide-user-plus',
    'user-x': 'lucide-user-x',
    'users': 'lucide-users',
    'verified': 'lucide-verified',
    'vertical-split': 'lucide-separator-vertical',
    'vertical-three-dots': 'lucide-more-vertical',
    'vibrate': 'lucide-vibrate',
    'video': 'lucide-video',
    'video-off': 'lucide-video-off',
    'view': 'lucide-view',
    'voicemail': 'lucide-voicemail',
    'volume': 'lucide-volume',
    'volume-1': 'lucide-volume-1',
    'volume-2': 'lucide-volume-2',
    'volume-x': 'lucide-volume-x',
    'wallet': 'lucide-wallet',
    'wand': 'lucide-wand-2',
    'watch': 'lucide-watch',
    'waves': 'lucide-waves',
    'webcam': 'lucide-webcam',
    'wifi': 'lucide-wifi',
    'wifi-off': 'lucide-wifi-off',
    'wind': 'lucide-wind',
    'wrap-text': 'lucide-wrap-text',
    'wrench': 'lucide-wrench',
    'wrench-screwdriver-glyph': 'lucide-wrench',
    'x': 'lucide-x',
    'x-circle': 'lucide-x-circle',
    'x-octagon': 'lucide-x-octagon',
    'x-square': 'lucide-x-square',
    'youtube': 'lucide-youtube',
    'zap': 'lucide-zap',
    'zap-off': 'lucide-zap-off',
    'zoom-in': 'lucide-zoom-in',
    'zoom-out': 'lucide-zoom-out',
};